// HSK 1 character list — hand-curated.
// pinyin: primary reading first (the HSK-1 reading), tone-marked.
// meanings: short learner-friendly glosses.
// topics: numbers | time | family | people | food | school | travel | weather | everyday
const c = (char, pinyin, meanings, topics) => ({
  char,
  pinyin: Array.isArray(pinyin) ? pinyin : [pinyin],
  meanings: Array.isArray(meanings) ? meanings : [meanings],
  topics,
});

export const CHARS = [
  // ---- numbers ----
  c("一", "yī", ["one"], ["numbers"]),
  c("二", "èr", ["two"], ["numbers"]),
  c("三", "sān", ["three"], ["numbers"]),
  c("四", "sì", ["four"], ["numbers"]),
  c("五", "wǔ", ["five"], ["numbers"]),
  c("六", "liù", ["six"], ["numbers"]),
  c("七", "qī", ["seven"], ["numbers"]),
  c("八", "bā", ["eight"], ["numbers"]),
  c("九", "jiǔ", ["nine"], ["numbers"]),
  c("十", "shí", ["ten"], ["numbers"]),
  c("零", "líng", ["zero"], ["numbers"]),
  c("百", "bǎi", ["hundred"], ["numbers"]),
  c("块", "kuài", ["yuan (money)", "piece; lump"], ["numbers", "everyday"]),
  c("钱", "qián", ["money"], ["numbers", "everyday"]),
  c("号", "hào", ["date; day of the month", "number"], ["numbers", "time"]),
  c("几", "jǐ", ["how many", "several"], ["numbers"]),
  c("多", "duō", ["many; much", "how (to what extent)"], ["numbers", "everyday"]),
  c("少", ["shǎo", "shào"], ["few; little"], ["numbers", "everyday"]),

  // ---- time ----
  c("天", "tiān", ["day", "sky"], ["time", "weather"]),
  c("年", "nián", ["year"], ["time"]),
  c("月", "yuè", ["month", "moon"], ["time"]),
  c("日", "rì", ["day", "sun"], ["time"]),
  c("时", "shí", ["time", "hour"], ["time"]),
  c("候", "hòu", ["time; moment (in 时候)"], ["time"]),
  c("分", ["fēn", "fèn"], ["minute", "to divide"], ["time"]),
  c("钟", "zhōng", ["clock", "o'clock (time)"], ["time"]),
  c("点", "diǎn", ["o'clock", "dot; a little"], ["time"]),
  c("今", "jīn", ["now; today (in 今天)"], ["time"]),
  c("明", "míng", ["bright", "next (in 明天)"], ["time"]),
  c("昨", "zuó", ["yesterday (in 昨天)"], ["time"]),
  c("星", "xīng", ["star", "week (in 星期)"], ["time"]),
  c("期", "qī", ["period of time", "week (in 星期)"], ["time"]),
  c("午", "wǔ", ["noon"], ["time"]),
  c("现", "xiàn", ["present; now (in 现在)"], ["time"]),
  c("在", "zài", ["at; in", "to be (somewhere)"], ["time", "everyday"]),

  // ---- family & people ----
  c("家", "jiā", ["home", "family"], ["family"]),
  c("爸", "bà", ["dad; father"], ["family"]),
  c("妈", "mā", ["mom; mother"], ["family"]),
  c("儿", ["ér", "r"], ["son; child"], ["family"]),
  c("女", "nǚ", ["female", "daughter (in 女儿)"], ["family", "people"]),
  c("子", ["zǐ", "zi"], ["child", "(noun suffix)"], ["family", "people"]),
  c("人", "rén", ["person; people"], ["people"]),
  c("朋", "péng", ["friend (in 朋友)"], ["people"]),
  c("友", "yǒu", ["friend"], ["people"]),
  c("我", "wǒ", ["I; me"], ["people"]),
  c("你", "nǐ", ["you"], ["people"]),
  c("他", "tā", ["he; him"], ["people"]),
  c("她", "tā", ["she; her"], ["people"]),
  c("们", "men", ["(plural suffix for people)"], ["people"]),
  c("先", "xiān", ["first", "Mr. (in 先生)"], ["people"]),
  c("生", "shēng", ["to be born", "student (in 学生)", "Mr. (in 先生)"], ["people", "school"]),
  c("小", "xiǎo", ["small; little", "Miss (in 小姐)"], ["people", "everyday"]),
  c("姐", "jiě", ["older sister", "Miss (in 小姐)"], ["family", "people"]),
  c("谁", ["shéi", "shuí"], ["who"], ["people"]),
  c("名", "míng", ["name"], ["people"]),
  c("字", "zì", ["character; word"], ["people", "school"]),
  c("医", "yī", ["doctor; medicine (in 医生)"], ["people"]),
  c("老", "lǎo", ["old", "teacher (in 老师)"], ["people", "school"]),
  c("师", "shī", ["teacher (in 老师)"], ["people", "school"]),
  c("同", "tóng", ["same", "classmate (in 同学)"], ["people", "school"]),

  // ---- food & drink ----
  c("吃", "chī", ["to eat"], ["food"]),
  c("喝", "hē", ["to drink"], ["food"]),
  c("茶", "chá", ["tea"], ["food"]),
  c("水", "shuǐ", ["water"], ["food"]),
  c("菜", "cài", ["dish (of food)", "vegetable"], ["food"]),
  c("饭", "fàn", ["cooked rice", "meal"], ["food"]),
  c("米", "mǐ", ["rice (uncooked)", "meter"], ["food"]),
  c("果", "guǒ", ["fruit"], ["food"]),
  c("苹", "píng", ["apple (in 苹果)"], ["food"]),
  c("杯", "bēi", ["cup; glass"], ["food"]),

  // ---- school & learning ----
  c("学", "xué", ["to learn; to study", "school (in 学校)"], ["school"]),
  c("习", "xí", ["to practice; to study (in 学习)"], ["school"]),
  c("校", "xiào", ["school (in 学校)"], ["school"]),
  c("书", "shū", ["book"], ["school"]),
  c("读", "dú", ["to read"], ["school"]),
  c("写", "xiě", ["to write"], ["school"]),
  c("本", "běn", ["(measure word for books)", "origin"], ["school"]),
  c("汉", "hàn", ["Chinese (in 汉语)", "Han ethnicity"], ["school"]),
  c("语", "yǔ", ["language"], ["school"]),
  c("说", "shuō", ["to speak; to say"], ["school", "everyday"]),
  c("听", "tīng", ["to listen"], ["school", "everyday"]),
  c("看", "kàn", ["to look; to watch; to read"], ["school", "everyday"]),

  // ---- places & travel ----
  c("中", "zhōng", ["middle; center", "China (in 中国)"], ["travel"]),
  c("国", "guó", ["country"], ["travel"]),
  c("北", "běi", ["north"], ["travel"]),
  c("京", "jīng", ["capital city (in 北京)"], ["travel"]),
  c("店", "diàn", ["shop; store"], ["travel", "everyday"]),
  c("商", "shāng", ["commerce; shop (in 商店)"], ["travel"]),
  c("院", "yuàn", ["courtyard", "hospital (in 医院)"], ["travel"]),
  c("车", "chē", ["car; vehicle"], ["travel"]),
  c("出", "chū", ["to go out"], ["travel"]),
  c("租", "zū", ["to rent", "taxi (in 出租车)"], ["travel"]),
  c("飞", "fēi", ["to fly"], ["travel"]),
  c("机", "jī", ["machine", "airplane (in 飞机)"], ["travel"]),
  c("火", "huǒ", ["fire", "train (in 火车)"], ["travel"]),
  c("站", "zhàn", ["station", "to stand"], ["travel"]),
  c("来", "lái", ["to come"], ["travel", "everyday"]),
  c("去", "qù", ["to go"], ["travel", "everyday"]),
  c("回", "huí", ["to return; to go back"], ["travel", "everyday"]),
  c("坐", "zuò", ["to sit", "to take (transport)"], ["travel", "everyday"]),
  c("开", "kāi", ["to open", "to drive"], ["travel", "everyday"]),
  c("住", "zhù", ["to live (somewhere)"], ["travel", "everyday"]),
  c("里", "lǐ", ["inside; in"], ["travel", "everyday"]),
  c("上", "shàng", ["up; on; above", "to go up"], ["everyday"]),
  c("下", "xià", ["down; below", "to go down"], ["everyday"]),
  c("前", "qián", ["front; before"], ["everyday"]),
  c("后", "hòu", ["behind; after"], ["everyday"]),
  c("面", "miàn", ["side; face", "noodles"], ["everyday"]),
  c("东", "dōng", ["east", "thing (in 东西)"], ["everyday"]),
  c("西", "xī", ["west", "thing (in 东西)"], ["everyday"]),

  // ---- weather ----
  c("气", "qì", ["air", "weather (in 天气)"], ["weather"]),
  c("热", "rè", ["hot"], ["weather"]),
  c("冷", "lěng", ["cold"], ["weather"]),
  c("雨", "yǔ", ["rain"], ["weather"]),

  // ---- everyday objects ----
  c("电", "diàn", ["electricity"], ["everyday"]),
  c("脑", "nǎo", ["brain", "computer (in 电脑)"], ["everyday"]),
  c("视", "shì", ["to look at", "TV (in 电视)"], ["everyday"]),
  c("影", "yǐng", ["shadow", "movie (in 电影)"], ["everyday"]),
  c("话", "huà", ["speech; words", "phone (in 电话)"], ["everyday"]),
  c("桌", "zhuō", ["table; desk"], ["everyday"]),
  c("椅", "yǐ", ["chair (in 椅子)"], ["everyday"]),
  c("衣", "yī", ["clothes"], ["everyday"]),
  c("服", "fú", ["clothes (in 衣服)"], ["everyday"]),
  c("猫", "māo", ["cat"], ["everyday"]),
  c("狗", "gǒu", ["dog"], ["everyday"]),

  // ---- core verbs / adjectives / grammar ----
  c("是", "shì", ["to be"], ["everyday"]),
  c("有", "yǒu", ["to have", "there is"], ["everyday"]),
  c("没", "méi", ["not (to not have)"], ["everyday"]),
  c("不", "bù", ["no; not"], ["everyday"]),
  c("好", ["hǎo", "hào"], ["good", "well"], ["everyday"]),
  c("大", "dà", ["big"], ["everyday"]),
  c("爱", "ài", ["to love", "love"], ["everyday", "family"]),
  c("想", "xiǎng", ["to want to", "to think; to miss"], ["everyday"]),
  c("要", "yào", ["to want", "will (future)"], ["everyday"]),
  c("会", "huì", ["can (know how to)", "meeting"], ["everyday"]),
  c("能", "néng", ["can; to be able to"], ["everyday"]),
  c("买", "mǎi", ["to buy"], ["everyday"]),
  c("做", "zuò", ["to do; to make"], ["everyday"]),
  c("工", "gōng", ["work"], ["everyday"]),
  c("作", "zuò", ["to do; work (in 工作)"], ["everyday"]),
  c("打", "dǎ", ["to hit", "to make (a phone call)"], ["everyday"]),
  c("叫", "jiào", ["to be called", "to call"], ["everyday"]),
  c("认", "rèn", ["to recognize (in 认识)"], ["everyday"]),
  c("识", "shí", ["to know (in 认识)"], ["everyday"]),
  c("见", "jiàn", ["to see; to meet"], ["everyday"]),
  c("睡", "shuì", ["to sleep"], ["everyday"]),
  c("觉", ["jiào", "jué"], ["sleep (in 睡觉)", "to feel (jué)"], ["everyday"]),
  c("喜", "xǐ", ["to like (in 喜欢)", "joy"], ["everyday"]),
  c("欢", "huān", ["joyful (in 喜欢)"], ["everyday"]),
  c("高", "gāo", ["tall; high", "happy (in 高兴)"], ["everyday"]),
  c("兴", ["xìng", "xīng"], ["excitement; happy (in 高兴)"], ["everyday"]),
  c("漂", ["piào", "piāo"], ["pretty (in 漂亮)"], ["everyday"]),
  c("亮", "liàng", ["bright", "pretty (in 漂亮)"], ["everyday"]),
  c("很", "hěn", ["very"], ["everyday"]),
  c("太", "tài", ["too (excessively)"], ["everyday"]),
  c("都", ["dōu", "dū"], ["all; both"], ["everyday"]),
  c("和", "hé", ["and", "with"], ["everyday"]),
  c("请", "qǐng", ["please", "to invite"], ["everyday"]),
  c("谢", "xiè", ["to thank"], ["everyday"]),
  c("对", "duì", ["correct", "toward (in 对不起)"], ["everyday"]),
  c("起", "qǐ", ["to rise; to get up"], ["everyday"]),
  c("客", "kè", ["guest", "polite (in 客气)"], ["everyday"]),
  c("关", "guān", ["to close", "relation (in 关系)"], ["everyday"]),
  c("系", ["xì", "jì"], ["system; relation (in 关系)"], ["everyday"]),
  c("再", "zài", ["again", "goodbye (in 再见)"], ["everyday"]),
  c("这", "zhè", ["this"], ["everyday"]),
  c("那", "nà", ["that"], ["everyday"]),
  c("哪", "nǎ", ["which", "where (in 哪儿)"], ["everyday"]),
  c("什", ["shén", "shí"], ["what (in 什么)"], ["everyday"]),
  c("么", "me", ["(suffix in 什么 / 怎么)"], ["everyday"]),
  c("怎", "zěn", ["how (in 怎么)"], ["everyday"]),
  c("样", "yàng", ["manner; appearance (in 怎么样)"], ["everyday"]),
  c("些", "xiē", ["some; a few"], ["everyday"]),
  c("的", ["de", "dì"], ["(possessive particle)"], ["everyday"]),
  c("了", ["le", "liǎo"], ["(completed-action particle)"], ["everyday"]),
  c("吗", "ma", ["(yes/no question particle)"], ["everyday"]),
  c("呢", "ne", ["(question particle: and ...?)"], ["everyday"]),
  c("喂", ["wéi", "wèi"], ["hello (on the phone)"], ["everyday"]),
  c("个", "gè", ["(general measure word)"], ["everyday"]),
  c("岁", "suì", ["years old"], ["everyday", "numbers"]),
];
