// Simple HSK 1 example sentences. Attached to character pages by inclusion.
const s = (zh, pinyin, en) => ({ zh, pinyin, en });

export const SENTENCES = [
  s("我爱你。", "Wǒ ài nǐ.", "I love you."),
  s("我是学生。", "Wǒ shì xuésheng.", "I am a student."),
  s("你好吗？", "Nǐ hǎo ma?", "How are you?"),
  s("我很好，你呢？", "Wǒ hěn hǎo, nǐ ne?", "I'm fine, and you?"),
  s("他是我的朋友。", "Tā shì wǒ de péngyou.", "He is my friend."),
  s("我喜欢喝茶。", "Wǒ xǐhuan hē chá.", "I like drinking tea."),
  s("今天天气很好。", "Jīntiān tiānqì hěn hǎo.", "The weather is nice today."),
  s("我去学校。", "Wǒ qù xuéxiào.", "I go to school."),
  s("她有一个女儿。", "Tā yǒu yí ge nǚ'ér.", "She has a daughter."),
  s("他有一个儿子。", "Tā yǒu yí ge érzi.", "He has a son."),
  s("我们明天见。", "Wǒmen míngtiān jiàn.", "See you tomorrow."),
  s("这是什么？", "Zhè shì shénme?", "What is this?"),
  s("那是我的书。", "Nà shì wǒ de shū.", "That is my book."),
  s("你叫什么名字？", "Nǐ jiào shénme míngzi?", "What is your name?"),
  s("我不吃米饭。", "Wǒ bù chī mǐfàn.", "I don't eat rice."),
  s("他在医院工作。", "Tā zài yīyuàn gōngzuò.", "He works at a hospital."),
  s("现在几点？", "Xiànzài jǐ diǎn?", "What time is it now?"),
  s("我想买苹果。", "Wǒ xiǎng mǎi píngguǒ.", "I want to buy apples."),
  s("猫在桌子下面。", "Māo zài zhuōzi xiàmiàn.", "The cat is under the table."),
  s("狗在家里。", "Gǒu zài jiā li.", "The dog is at home."),
  s("我会说汉语。", "Wǒ huì shuō Hànyǔ.", "I can speak Chinese."),
  s("请坐。", "Qǐng zuò.", "Please sit down."),
  s("谢谢你！", "Xièxie nǐ!", "Thank you!"),
  s("不客气。", "Bú kèqi.", "You're welcome."),
  s("对不起。", "Duìbuqǐ.", "Sorry."),
  s("没关系。", "Méi guānxi.", "It's okay."),
  s("再见！", "Zàijiàn!", "Goodbye!"),
  s("我住在北京。", "Wǒ zhù zài Běijīng.", "I live in Beijing."),
  s("他是中国人。", "Tā shì Zhōngguó rén.", "He is Chinese."),
  s("今天是星期日。", "Jīntiān shì xīngqīrì.", "Today is Sunday."),
  s("我今年二十岁。", "Wǒ jīnnián èrshí suì.", "I am twenty years old."),
  s("这个多少钱？", "Zhège duōshao qián?", "How much is this?"),
  s("太好了！", "Tài hǎo le!", "Great!"),
  s("我在看电视。", "Wǒ zài kàn diànshì.", "I am watching TV."),
  s("他喜欢看电影。", "Tā xǐhuan kàn diànyǐng.", "He likes watching movies."),
  s("妈妈在做饭。", "Māma zài zuò fàn.", "Mom is cooking."),
  s("爸爸喝水。", "Bàba hē shuǐ.", "Dad drinks water."),
  s("我坐飞机去北京。", "Wǒ zuò fēijī qù Běijīng.", "I take a plane to Beijing."),
  s("他开出租车。", "Tā kāi chūzūchē.", "He drives a taxi."),
  s("老师在学校。", "Lǎoshī zài xuéxiào.", "The teacher is at school."),
  s("我下午去商店。", "Wǒ xiàwǔ qù shāngdiàn.", "I'm going to the shop in the afternoon."),
  s("今天下雨了。", "Jīntiān xià yǔ le.", "It rained today."),
  s("天气很冷。", "Tiānqì hěn lěng.", "The weather is cold."),
  s("天气太热了。", "Tiānqì tài rè le.", "The weather is too hot."),
  s("你听，谁在说话？", "Nǐ tīng, shéi zài shuōhuà?", "Listen, who is speaking?"),
  s("我想睡觉。", "Wǒ xiǎng shuìjiào.", "I want to sleep."),
  s("你住在哪儿？", "Nǐ zhù zài nǎr?", "Where do you live?"),
  s("他昨天回家了。", "Tā zuótiān huí jiā le.", "He went home yesterday."),
  s("我认识她。", "Wǒ rènshi tā.", "I know her."),
  s("你能来吗？", "Nǐ néng lái ma?", "Can you come?"),
  s("我们是同学。", "Wǒmen shì tóngxué.", "We are classmates."),
  s("她很漂亮。", "Tā hěn piàoliang.", "She is very pretty."),
  s("我读书。", "Wǒ dú shū.", "I read books."),
  s("请写你的名字。", "Qǐng xiě nǐ de míngzi.", "Please write your name."),
  s("喂，你好！", "Wéi, nǐ hǎo!", "Hello (on the phone)!"),
  s("这些东西是谁的？", "Zhèxiē dōngxi shì shéi de?", "Whose things are these?"),
  s("先生，你好！", "Xiānsheng, nǐ hǎo!", "Hello, sir!"),
  s("我们上午九点开会。", "Wǒmen shàngwǔ jiǔ diǎn kāihuì.", "We have a meeting at nine in the morning."),
  s("小姐，请喝茶。", "Xiǎojiě, qǐng hē chá.", "Miss, please have some tea."),
  s("火车站在前面。", "Huǒchēzhàn zài qiánmiàn.", "The train station is ahead."),
  s("商店在饭店后面。", "Shāngdiàn zài fàndiàn hòumiàn.", "The shop is behind the restaurant."),
  s("我有一本书。", "Wǒ yǒu yì běn shū.", "I have a book."),
  s("杯子里有水。", "Bēizi li yǒu shuǐ.", "There is water in the cup."),
  s("椅子上有一个杯子。", "Yǐzi shang yǒu yí ge bēizi.", "There is a cup on the chair."),
  s("他们是好朋友。", "Tāmen shì hǎo péngyou.", "They are good friends."),
  s("现在是中午。", "Xiànzài shì zhōngwǔ.", "It is noon now."),
  s("一年有十二个月。", "Yì nián yǒu shí'èr ge yuè.", "A year has twelve months."),
  s("一个星期有七天。", "Yí ge xīngqī yǒu qī tiān.", "A week has seven days."),
  s("你几岁？", "Nǐ jǐ suì?", "How old are you?"),
  s("这是三块钱。", "Zhè shì sān kuài qián.", "This is three yuan."),
  s("我买了五个苹果。", "Wǒ mǎi le wǔ ge píngguǒ.", "I bought five apples."),
  s("今天是三月九号。", "Jīntiān shì sān yuè jiǔ hào.", "Today is March 9th."),
  s("你的电话是多少？", "Nǐ de diànhuà shì duōshao?", "What is your phone number?"),
  s("这是我的电脑。", "Zhè shì wǒ de diànnǎo.", "This is my computer."),
  s("你想吃什么菜？", "Nǐ xiǎng chī shénme cài?", "What dish do you want to eat?"),
  s("她的衣服很漂亮。", "Tā de yīfu hěn piàoliang.", "Her clothes are very pretty."),
  s("五分钟后见。", "Wǔ fēnzhōng hòu jiàn.", "See you in five minutes."),
  s("认识你很高兴。", "Rènshi nǐ hěn gāoxìng.", "Nice to meet you."),
  s("这个字怎么写？", "Zhège zì zěnme xiě?", "How do you write this character?"),
  s("明天去怎么样？", "Míngtiān qù zěnmeyàng?", "How about going tomorrow?"),
  s("你什么时候来？", "Nǐ shénme shíhou lái?", "When are you coming?"),
  s("我喜欢吃水果。", "Wǒ xǐhuan chī shuǐguǒ.", "I like eating fruit."),
  s("我在学习汉语。", "Wǒ zài xuéxí Hànyǔ.", "I am studying Chinese."),
  s("我有很多书。", "Wǒ yǒu hěn duō shū.", "I have many books."),
  s("人很少。", "Rén hěn shǎo.", "There are very few people."),
  s("我要一杯水。", "Wǒ yào yì bēi shuǐ.", "I want a glass of water."),
  s("六月一号是星期一。", "Liù yuè yī hào shì xīngqīyī.", "June 1st is a Monday."),
  s("我家有四口人。", "Wǒ jiā yǒu sì kǒu rén.", "There are four people in my family."),
  s("一百块钱。", "Yìbǎi kuài qián.", "One hundred yuan."),
  s("现在是零下十度。", "Xiànzài shì líng xià shí dù.", "It is minus ten degrees now."),
  s("老师喜欢喝咖啡吗？", "Lǎoshī xǐhuan hē kāfēi ma?", "Does the teacher like coffee?"),
  s("现在八点。", "Xiànzài bā diǎn.", "It is eight o'clock."),
  s("中国很大。", "Zhōngguó hěn dà.", "China is very big."),
  s("他在打电话。", "Tā zài dǎ diànhuà.", "He is making a phone call."),
  s("他和我都是学生。", "Tā hé wǒ dōu shì xuésheng.", "He and I are both students."),
];

// Similar / easily-confused character groups (all chars must exist in CHARS).
export const SIMILAR_GROUPS = [
  ["大", "太", "天"],
  ["上", "下"],
  ["哪", "那"],
  ["几", "九"],
  ["儿", "几"],
  ["他", "她"],
  ["妈", "吗"],
  ["二", "三"],
  ["人", "八"],
  ["十", "七"],
  ["午", "年"],
  ["见", "现"],
  ["日", "月"],
  ["买", "头"],
  ["米", "来"],
  ["火", "人"],
  ["水", "小"],
  ["白", "百"],
  ["王", "五"],
  ["今", "个"],
];
