// HSK 1 vocabulary — used to attach example words to each character page.
const w = (word, pinyin, meaning) => ({ word, pinyin, meaning });

export const WORDS = [
  w("爱", "ài", "to love"),
  w("八", "bā", "eight"),
  w("爸爸", "bàba", "dad"),
  w("杯子", "bēizi", "cup; glass"),
  w("北京", "Běijīng", "Beijing"),
  w("本", "běn", "(measure word for books)"),
  w("不", "bù", "no; not"),
  w("不客气", "bú kèqi", "you're welcome"),
  w("菜", "cài", "dish; vegetable"),
  w("茶", "chá", "tea"),
  w("吃", "chī", "to eat"),
  w("出租车", "chūzūchē", "taxi"),
  w("打电话", "dǎ diànhuà", "to make a phone call"),
  w("大", "dà", "big"),
  w("的", "de", "(possessive particle)"),
  w("点", "diǎn", "o'clock"),
  w("电脑", "diànnǎo", "computer"),
  w("电话", "diànhuà", "telephone"),
  w("电视", "diànshì", "television"),
  w("电影", "diànyǐng", "movie"),
  w("东西", "dōngxi", "thing; stuff"),
  w("都", "dōu", "all; both"),
  w("读", "dú", "to read"),
  w("对不起", "duìbuqǐ", "sorry"),
  w("多", "duō", "many; much"),
  w("多少", "duōshao", "how many; how much"),
  w("儿子", "érzi", "son"),
  w("二", "èr", "two"),
  w("饭店", "fàndiàn", "restaurant; hotel"),
  w("飞机", "fēijī", "airplane"),
  w("分钟", "fēnzhōng", "minute"),
  w("高兴", "gāoxìng", "happy; glad"),
  w("个", "gè", "(general measure word)"),
  w("工作", "gōngzuò", "work; job"),
  w("狗", "gǒu", "dog"),
  w("汉语", "Hànyǔ", "Chinese language"),
  w("好", "hǎo", "good"),
  w("号", "hào", "date; number"),
  w("喝", "hē", "to drink"),
  w("和", "hé", "and"),
  w("很", "hěn", "very"),
  w("后面", "hòumiàn", "behind"),
  w("回", "huí", "to return"),
  w("会", "huì", "can; to know how to"),
  w("火车站", "huǒchēzhàn", "train station"),
  w("几", "jǐ", "how many; several"),
  w("家", "jiā", "home; family"),
  w("叫", "jiào", "to be called"),
  w("今天", "jīntiān", "today"),
  w("九", "jiǔ", "nine"),
  w("开", "kāi", "to open; to drive"),
  w("看", "kàn", "to look; to watch"),
  w("看见", "kànjiàn", "to see"),
  w("块", "kuài", "yuan (measure word for money)"),
  w("来", "lái", "to come"),
  w("老师", "lǎoshī", "teacher"),
  w("了", "le", "(completed-action particle)"),
  w("冷", "lěng", "cold"),
  w("里", "lǐ", "inside"),
  w("零", "líng", "zero"),
  w("六", "liù", "six"),
  w("妈妈", "māma", "mom"),
  w("吗", "ma", "(question particle)"),
  w("买", "mǎi", "to buy"),
  w("猫", "māo", "cat"),
  w("没关系", "méi guānxi", "it doesn't matter"),
  w("没有", "méiyǒu", "to not have"),
  w("米饭", "mǐfàn", "cooked rice"),
  w("明天", "míngtiān", "tomorrow"),
  w("名字", "míngzi", "name"),
  w("哪", "nǎ", "which"),
  w("哪儿", "nǎr", "where"),
  w("那", "nà", "that"),
  w("呢", "ne", "(question particle)"),
  w("能", "néng", "can; to be able to"),
  w("你", "nǐ", "you"),
  w("年", "nián", "year"),
  w("女儿", "nǚ'ér", "daughter"),
  w("朋友", "péngyou", "friend"),
  w("漂亮", "piàoliang", "pretty; beautiful"),
  w("苹果", "píngguǒ", "apple"),
  w("七", "qī", "seven"),
  w("前面", "qiánmiàn", "in front"),
  w("钱", "qián", "money"),
  w("请", "qǐng", "please; to invite"),
  w("去", "qù", "to go"),
  w("热", "rè", "hot"),
  w("人", "rén", "person"),
  w("认识", "rènshi", "to know (someone)"),
  w("日", "rì", "day; date"),
  w("三", "sān", "three"),
  w("商店", "shāngdiàn", "shop; store"),
  w("上", "shàng", "up; on"),
  w("上午", "shàngwǔ", "morning"),
  w("少", "shǎo", "few; little"),
  w("谁", "shéi", "who"),
  w("什么", "shénme", "what"),
  w("十", "shí", "ten"),
  w("时候", "shíhou", "time; moment"),
  w("是", "shì", "to be"),
  w("书", "shū", "book"),
  w("水", "shuǐ", "water"),
  w("水果", "shuǐguǒ", "fruit"),
  w("睡觉", "shuìjiào", "to sleep"),
  w("说", "shuō", "to speak"),
  w("四", "sì", "four"),
  w("岁", "suì", "years old"),
  w("他", "tā", "he; him"),
  w("她", "tā", "she; her"),
  w("太", "tài", "too (excessively)"),
  w("天气", "tiānqì", "weather"),
  w("听", "tīng", "to listen"),
  w("同学", "tóngxué", "classmate"),
  w("喂", "wéi", "hello (on the phone)"),
  w("我", "wǒ", "I; me"),
  w("我们", "wǒmen", "we; us"),
  w("五", "wǔ", "five"),
  w("喜欢", "xǐhuan", "to like"),
  w("下", "xià", "down; below"),
  w("下午", "xiàwǔ", "afternoon"),
  w("下雨", "xià yǔ", "to rain"),
  w("先生", "xiānsheng", "Mr.; sir"),
  w("现在", "xiànzài", "now"),
  w("想", "xiǎng", "to want to; to think"),
  w("小", "xiǎo", "small"),
  w("小姐", "xiǎojiě", "Miss"),
  w("些", "xiē", "some"),
  w("写", "xiě", "to write"),
  w("谢谢", "xièxie", "thanks"),
  w("星期", "xīngqī", "week"),
  w("学生", "xuésheng", "student"),
  w("学习", "xuéxí", "to study"),
  w("学校", "xuéxiào", "school"),
  w("一", "yī", "one"),
  w("一百", "yìbǎi", "one hundred"),
  w("衣服", "yīfu", "clothes"),
  w("医生", "yīshēng", "doctor"),
  w("医院", "yīyuàn", "hospital"),
  w("椅子", "yǐzi", "chair"),
  w("有", "yǒu", "to have"),
  w("月", "yuè", "month"),
  w("再见", "zàijiàn", "goodbye"),
  w("在", "zài", "at; in"),
  w("怎么", "zěnme", "how"),
  w("怎么样", "zěnmeyàng", "how about; how is it"),
  w("这", "zhè", "this"),
  w("中国", "Zhōngguó", "China"),
  w("中午", "zhōngwǔ", "noon"),
  w("住", "zhù", "to live (somewhere)"),
  w("桌子", "zhuōzi", "table; desk"),
  w("字", "zì", "character; word"),
  w("昨天", "zuótiān", "yesterday"),
  w("坐", "zuò", "to sit"),
  w("做", "zuò", "to do; to make"),
  w("要", "yào", "to want; will"),
];
